### ISSUE TITLE
SPDB is not correct

### ISSUE THREAD

**Issue by bemda** [QuantConnect/Lean#8556]
Hi QC team,

we have this problem in production trading, SPDB (symbol-properties-database.csv) contains errors.

We are using lean-cli, the strategy is running locally.

The following happened:

1. We restarted the strategy via LEAN-CLI (with --no-update parameter).
2. When the Lean-cli strategy started, it downloaded a new version of symbol-properties-database.csv. 
3. However, there is an incorrect entry in this file, specifically for the Bybit exchange

Data through Lean-cli:
bybit,BNBUSDT,cryptofuture,BNBUSDT,USDT,1,**0.50**,0.01,BNBUSDT,0.01
 
Correct data from the Bybit exchange:
bybit,BNBUSDT,cryptofuture,BNBUSDT,USDT,1,**0.05**,0.01,BNBUSDT,0.01
 
4. We have several strategies running locally as separate Lean instances. SPDB is implicitly shared for all strategies and Lean automatically refreshes this file in the strategies. 
 
5. Thus, the bug got into all running strategies on production and caused us problems. 
 

Problem
When analyzing the bug in more detail, we found that the symbol-properties-database.csv (SPDB) file that is automatically refreshed from Quantconnect's GitHub when a strategy is run via lean-cli does not match reality in a lot of other data - it contains an outdated asset list. Specifically, we checked the Bybit exchange.

**Comment by Romazes** [comment]
Hey, @bemda 

Endpoint: https://api-testnet.bybit.com/v5/market/instruments-info?category=linear&symbol=BNBUSDT
```
{
  "retCode": 0,
  "retMsg": "OK",
  "result": {
    "category": "linear",
    "list": [
      {
        "symbol": "BNBUSDT",
        "contractType": "LinearPerpetual",
        "status": "Trading",
        "baseCoin": "BNB",
        "quoteCoin": "USDT",
        "launchTime": "1688701632000",
        "deliveryTime": "0",
        "deliveryFeeRate": "",
        "priceScale": "2",
        "leverageFilter": {
          "minLeverage": "1",
          "maxLeverage": "25.00",
          "leverageStep": "0.01"
        },
        "priceFilter": {
          "minPrice": "0.50",
          "maxPrice": "9999999.00",
          "tickSize": "0.50"
        },
        "lotSizeFilter": {
          "maxOrderQty": "5120.00",
          "minOrderQty": "0.01",
          "qtyStep": "0.01",
          "postOnlyMaxOrderQty": "5120.00",
          "maxMktOrderQty": "1054.00",
          "minNotionalValue": "5"
        },
        "unifiedMarginTrade": true,
        "fundingInterval": 480,
        "settleCoin": "USDT",
        "copyTrading": "both",
        "upperFundingRate": "0.0075",
        "lowerFundingRate": "-0.0075",
        "isPreListing": false,
        "preListingInfo": null,
        "riskParameters": {
          "priceLimitRatioX": "0.02",
          "priceLimitRatioY": "0.04"
        }
      }
    ],
    "nextPageCursor": ""
  },
  "retExtInfo": {

  },
  "time": 1738016208711
}
```

Endpoint: https://api.bybit.com/v5/market/instruments-info?category=linear&symbol=BNBUSDT
```
{ 
  "retCode": 0,
  "retMsg": "OK",
  "result": {
    "category": "linear",
    "list": [
      {
        "symbol": "BNBUSDT",
        "contractType": "LinearPerpetual",
        "status": "Trading",
        "baseCoin": "BNB",
        "quoteCoin": "USDT",
        "launchTime": "1624951080000",
        "deliveryTime": "0",
        "deliveryFeeRate": "",
        "priceScale": "2",
        "leverageFilter": {
          "minLeverage": "1",
          "maxLeverage": "50.00",
          "leverageStep": "0.01"
        },
        "priceFilter": {
          "minPrice": "0.05",
          "maxPrice": "999999.90",
          "tickSize": "0.05"
        },
        "lotSizeFilter": {
          "maxOrderQty": "5120.00",
          "minOrderQty": "0.01",
          "qtyStep": "0.01",
          "postOnlyMaxOrderQty": "5120.00",
          "maxMktOrderQty": "1054.00",
          "minNotionalValue": "5"
        },
        "unifiedMarginTrade": true,
        "fundingInterval": 480,
        "settleCoin": "USDT",
        "copyTrading": "both",
        "upperFundingRate": "0.0075",
        "lowerFundingRate": "-0.0075",
        "isPreListing": false,
        "preListingInfo": null,
        "riskParameters": {
          "priceLimitRatioX": "0.02",
          "priceLimitRatioY": "0.04"
        }
      }
    ],
    "nextPageCursor": ""
  },
  "retExtInfo": {

  },
  "time": 1738016143752
}
```
# Potential Solution
![Image](https://github.com/user-attachments/assets/d5cee77b-8623-426e-bf8f-164cc860392f)

**Comment by Martin-Molinero** [comment]
Thank you for the report, the issue has been fixed

> The following happened:
> 
> We restarted the strategy via LEAN-CLI (with --no-update parameter).
> When the Lean-cli strategy started, it downloaded a new version of symbol-properties-database.csv.
> However, there is an incorrect entry in this file, specifically for the Bybit exchange

Please take a look at [data updates](https://www.quantconnect.com/docs/v2/lean-cli/datasets/format-and-storage#04-Data-Updates) to disable automatic updates. See related https://github.com/QuantConnect/lean-cli/issues/470, we will look into making it a cli config and respecting --no-update flag

**Comment by bemda** [comment]
Hi Team-QC

Thank you very much for your quick response. Also thank you for the correction, BNBUSDT has the correct values now.

Unfortunately SPDB is still not up to date. Thus, the same error can occur - one strategy restarts and downloads the NOT up to date SPDB and this affects the other strategies. 

There are many outdated assets, for example AIDOGEUSDT or AKROUSDT

Here we see that this one does not exist at all
https://api.bybit.com/v5/market/instruments-info?category=linear&symbol=AIDOGEUSDT

Here we see that this one is in the closed state
https://api.bybit.com/v5/market/instruments-info?category=linear&symbol=AKROUSDT

We wonder what is the process of updating this file on GitHub and if it goes through any validation ? Since our production strategies rely on it, we need to understand this process and act accordingly. 

Could you describe that, please ?

**Comment by bemda** [comment]
Hello Team-QC once again, 

Exchanges like Bybit change asset parameters very frequently, so we also know what the best practices are to update the local SPDB correctly and regularly (on an intraday basis).

What is the recommended way to keep the SPDB up to date ?

**Comment by bemda** [comment]
> Thank you for the report, the issue has been fixed
> 
> > The following happened:
> > We restarted the strategy via LEAN-CLI (with --no-update parameter).
> > When the Lean-cli strategy started, it downloaded a new version of symbol-properties-database.csv.
> > However, there is an incorrect entry in this file, specifically for the Bybit exchange
> 
> Please take a look at [data updates](https://www.quantconnect.com/docs/v2/lean-cli/datasets/format-and-storage#04-Data-Updates) to disable automatic updates. See related [QuantConnect/lean-cli#470](https://github.com/QuantConnect/lean-cli/issues/470), we will look into making it a cli config and respecting --no-update flag



Hello Team-QC once again,

Exchanges like Bybit change asset parameters very frequently, so we also know what the best practices are to update the local SPDB correctly and regularly (on an intraday basis).

What is the recommended way to keep the SPDB up to date ?
